### ISSUE TITLE
一些使用体验

### ISSUE THREAD

**Issue by CMHopeSunshine** [nonepkg/nonebot-plugin-all4one#21]
尝试了一下将onebot v11转为onebot v12，讲讲使用体验
1. 使用时必须同时注册v11和v12的适配器，并且`obimpl_connections`配置中的`self_id_prefix`要为True(否则的话nb会报` Duplicate bot connection with id xxxx`)，这样bot_id里会带上`a4o@`，得手动去除a4o@来取纯bot_id，稍微麻烦)，有没有办法能够直接省去注册v11或让bot_id不带a4o也能用呢？
2. 日志有亿点刷屏，每一下心跳包跳出来好几条日志
![image](https://user-images.githubusercontent.com/63870437/227878553-182ec863-4447-44e3-b2a2-4a3e8cd32bb1.png)
如果能够在插件上过滤一下就好了。

没细看all4one的实现方式，如果上述有和设计思想冲突的或说错了的，还望指正。
期待all4one越来越完善，给插件带来更好的多平台适配方式~

**Comment by he0119** [comment]
也许你用 <https://github.com/he0119/OneBot-Impl-Docker#nonebot-all4one> 这个就能解决你的所有问题了。不过这样就相当于再部署一个 nb 充当实现。

1. 这个感觉无法避免，因为 nb 必须要有 v11 的适配器才能获取到事件，all4one 才有机会将 v11 的事件转成 v12 的。
2. 心跳也许只有关闭才能避免日志的出现。

**Comment by CMHopeSunshine** [comment]
不知是否能够通过插件自身进行ws连接（不经适配器）至`/onebot/v11/ws`进行事件转换呢

**Comment by he0119** [comment]
> 不知是否能够通过插件自身进行ws连接（不经适配器）至`/onebot/v11/ws`进行事件转换呢

这样就不算 nb 的插件了吧（

我自己平时是把它作为一个单独的实现来用的。

qqguild -> all4one -> bot 这种感觉。

**Comment by CMHopeSunshine** [comment]
好像也是...可以直接当适配器了）
感谢解答~

**Comment by j1g5awi** [comment]
> 不知是否能够通过插件自身进行ws连接（不经适配器）至`/onebot/v11/ws`进行事件转换呢

如果 OneBot V11 中間件這樣做的話，相当於  041 要獨自实現 OneBot V11 适配器的连接逻辑，浪费了 NoneBot2 已有的适配器资源。更何况 041 不止有 OneBot V11 中間件，Telegram、QQGuild 适配器的连接逻辑又与 OneBot V11 有极大的不同，每多一個平臺就加重一次开发者的负担。
